csp-sdk.release.info=Release8.0.0
csp-sdk.release.number=8000
csp-sdk.release.version=8.1.0-SNAPSHOT
csp-sdk.release.main=8000
csp-sdk.release.service=8000
csp-sdk.release.type=main
csp-sdk.git.branch=main
csp-sdk.git.tag=
csp-sdk.git.commit=ad0f4f8
csp-sdk.git.commit.full=ad0f4f871827e9e2c910dd08a547a602ae7e1d07
csp-sdk.git.buildtime=2026-04-02 15:21:09
csp-sdk.csp-sdk-core.version=8.1.0-SNAPSHOT
csp-sdk.csp-sdk-core.version=8.1.0-SNAPSHOT
csp-sdk.build.user=
csp-sdk.build.url=