server.port=8800
server.servlet.context-path=/

spring.mvc.pathmatch.matching-strategy=ant-path-matcher
spring.mvc.async.request-timeout=120000

logging.level.com.ovaledge.csp.apps=INFO
logging.level.root=INFO

spring.main.allow-bean-definition-overriding=true
